Repository process-analytics/icpm-demo-2022, pull requests merged in 2022-10, with the labels that each got.

#43 [FIX] Make possible to run the demo in Offline mode
  index.html
  package-lock.json
  package.json
Labels: bug

#46 [FIX] The reset button also resets the state of the other buttons
  src/buttons.js
Labels: bug

#47 [FIX] Fix the click on the `reset` button when the happy path is not shown
  src/buttons.js
Labels: bug

#50 chore: deploy PR preview to Surge
  .github/actions/build/action.yml
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy-pr-preview.yml
  package.json
Labels: chore

#51 chore: ensure Pull Request title follows "conventional commits"
  .github/workflows/pr-metadata-checks.yml
Labels: chore

#52 feat: add favicon
  index.html
  src/assets/favicon.svg
  src/assets/styles.css
Labels: enhancement

#53 deps: remove the unused 'animejs' dependency
  package-lock.json
  package.json
Labels: chore

#69 feat(happy-path): highlight elements less linearly
  src/happy-path.js
Labels: enhancement

#66 feat: update stroke width
  src/assets/styles.css
Labels: enhancement

#73 feat: remove the diagram title
  index.html
  src/assets/styles.css
  src/diagram.js
Labels: enhancement

#67 feat: improve overlay style
  src/conformance.js
Labels: enhancement

#75 refactor: remove unused MutationObserver code
  src/index.js
Labels: refactoring

#76 fix: ensure all edges are visually attached to shapes in the main BPMN diagram
  src/diagrams/EC-purchase-orders-collapsed.bpmn
Labels: bug

#78 feat: change background color
  index.html
  src/assets/styles.css
Labels: enhancement

#79 fix(happy-path): make the overlay fully visible
  src/happy-path.js
  src/index.js
Labels: bug

#81 chore: configure GH auto-generated release notes
  .github/release.yml
Labels: chore

#82 chore: clean the package.json file
  package.json
Labels: chore, refactoring
