Repository process-analytics/icpm-demo-2022, pull requests merged in 2023-09, with the labels that each got.

#85 feat: compliance rules highlight activities on popover click
  src/assets/styles.css
  src/bpmnElements.js
  src/compliance-rules.js
  src/complianceData.js
Labels: enhancement

#101 fix: match page title to conference name
  index.html
Labels: bug

#103 docs: add a "release how-to" paragraph in README
  README.md
  docs/github-logo.svg
Labels: documentation
